version: '3.1'

services:
  db:
    container_name: mariadb
    image: mariadb:11.2.4-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  adminer:
    container_name: adminer
    image: adminer:4.8.0
    restart: always
    ports:
      - 9080:8080

  smtp4dev:
    container_name: smtp4dev
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      - 9081:80
      - 9025:25
      - 143:143